### ISSUE TITLE
apache and nginx are using same port(80)

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megdc#47]
Megamnilavu uses nginx and port 80. Cobbler uses apache2 and port 80. When cobbler installation, it shows an error address(80) already in use.

**Comment by indykish** [comment]
@thomasalrin  Recommend you to convert everything to nginx.

http://givens.io/2012/12/cobbler-uwsgi-and-nginx/

**Comment by indykish** [comment]
@thomasalrin close this issue
