### ISSUE TITLE
Load static dns from dhcp

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megdc#51]
To avoid entering manual network configuration

**Comment by indykish** [comment]
preseed fix

**Comment by indykish** [comment]
Better yet, we can do the following.
- If the first CIB base server node boots using dhcp, then when we install `cobblerd`, you grab the `ip` and stick it as a `auto ..static` ip in the /etc/network/interfaces.

*If the first CIB base server node boots using static, then it ain't a problem.

This is needed just so the second node boots using the dhcp present in the first server node.
