### ISSUE TITLE
more than one sqlite record for megam

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megdc#54]
sqlite> select \* from servers;
1|MEGAM|1|||
2|COBBLER|1||Sep 9, 2014 at 12:01pm (EDT)|Sep 9, 2014 at 12:01pm (EDT)
4|MEGAM|1||Sep 12, 2014 at 6:08am (EDT)|Sep 12, 2014 at 6:08am (EDT)
5|MEGAM|1||Sep 12, 2014 at 6:08am (EDT)|Sep 12, 2014 at 6:08am (EDT)
6|MEGAM|1||Sep 12, 2014 at 6:09am (EDT)|Sep 12, 2014 at 6:09am (EDT)
8|MEGAM|1||Sep 12, 2014 at 6:15am (EDT)|Sep 12, 2014 at 6:15am (EDT)
9|MEGAM|1||Sep 12, 2014 at 7:34am (EDT)|Sep 12, 2014 at 7:34am (EDT)
10|MEGAM|1||Sep 12, 2014 at 7:35am (EDT)|Sep 12, 2014 at 7:35am (EDT)

**Comment by rajthilakmca** [comment]
@thomasalrin not multi entry in my testing, will be verify our test production
