### ISSUE TITLE
create our own /usr/share/one/install_gems

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/megdc#55]
Currently we write https://github.com/OpenNebula/one/blob/master/share/install_gems/install_gems  somewhere in our system. Ans in one_postinstall script we copy it to /usr/share/one/install_gems

**Comment by indykish** [comment]
After installing opennebula packager, use your own `install_gems` and overwrite it.

**Comment by indykish** [comment]
@thomasalrin close this issue
